### ISSUE TITLE
Become comrades with fellow library maintainers

### ISSUE THREAD

**Issue by patcon** [arturogutierrez/Badges#7]
https://github.com/leolin310148/ShortcutBadger

Projects seem very similar. On the off-chance you weren't aware of each other, just wanted to point it out :)

cc: @arturogutierrez @ffgiraldez @leolin310148 @MajeurAndroid @evgeniysharafan

**Comment by arturogutierrez** [comment]
I didn't know! Thanks for pointing it out, and yes, the projects are very similar, even seems forks!

**Comment by ffgiraldez** [comment]
should be great to add all those launcher badges
